### ISSUE TITLE
getReadings error at initialization

### ISSUE THREAD

**Issue by aliman17** [nervousnet/nervousnet-android#1]
The error that shows is pasted below. After a while it worked well for all sensors light, noise and battery. 

```
08-24 13:40:29.005 18040-18059/? E/JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
                                               java.lang.ClassCastException: java.util.Collections$EmptyList cannot be cast to java.util.ArrayList
                                                   at ch.ethz.coss.nervousnet.vm.storage.SQLHelper.getSensorReadings(SQLHelper.java:301)
                                                   at ch.ethz.coss.nervousnet.vm.NervousnetVM.getReadings(NervousnetVM.java:349)
                                                   at ch.ethz.coss.nervousnet.hub.NervousnetHubApiService$1.getReadings(NervousnetHubApiService.java:71)
                                                   at ch.ethz.coss.nervousnet.lib.NervousnetRemote$Stub.onTransact(NervousnetRemote.java:91)
                                                   at android.os.Binder.execTransact(Binder.java:446)
```

**Comment by prasad79** [comment]
Already resolved
